export const Questions = [
  {
    id:0,
    prompt: "Which word start with 'P' and ends with 'O'?",
    optionA: "John",
    optionB: "Jake",
    optionC: "Josh",
    optionD: "Pedro",
    asnwer: "optionD",
    answ: "Pedro",
  },
  {
    id:1,
    prompt: "Which of this is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "MC-03",
    optionD: "Java",
    asnwer: "optionC",
    answ: "MC-03",
  },
  {
    id:2,
    prompt: "Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
    answ: "Java",
  },
  {
    id:3,
    prompt: "Grand Central Terminal, Park Avenue, New York is the world's?",
    optionA: "largest railway station",
    optionB: "highest railway station",
    optionC: "longest railway station",
    optionD: "None of the above",
    asnwer: "optionA",
    answ: "largest railway station",
  },
  {
    id:4,
    prompt: "Entomology is the science that studies?",
    optionA: "Behavior of human beings",
    optionB: "Insects",
    optionC: "The origin and history of technical and scientific terms",
    optionD: "The formation of rocks",
    asnwer: "optionB",
    answ: "Insects",
  },
  {
    id:5,
    prompt: "Eritrea, which became the 182nd member of the UN in 1993, is in the continent of?",
    optionA: "Asia",
    optionB: "Africa",
    optionC: "Europe",
    optionD: "Australia",
    asnwer: "optionB",
    answ: "Africa",
  },
  {
    id:6,
    prompt: "Garampani sanctuary is located at?",
    optionA: "Junagarh, Gujarat",
    optionB: "Diphu, Assam",
    optionC: "Kohima, Nagaland",
    optionD: "Gangtok, Sikkim",
    asnwer: "optionB",
    answ: "Diphu, Assam",
  },
  {
    id:7,
    prompt: "For which of the following disciplines is Nobel Prize awarded??",
    optionA: "Physics and Chemistry",
    optionB: "Physiology or Medicine",
    optionC: "Literature, Peace and Economics",
    optionD: "All of the above",
    asnwer: "optionD",
    answ: "All of the above",
  },
  {
    id:8,
    prompt: "Hitler party which came into power in 1933 is known as?",
    optionA: "Labour Party",
    optionB: "Nazi Party",
    optionC: "Ku-Klux-Klan",
    optionD: "Democratic Party",
    asnwer: "optionB",
    answ: "Nazi Party",
  },
  {
    id:9,
    prompt: "Golf player Vijay Singh belongs to which country??",
    optionA: "USA",
    optionB: "Fiji",
    optionC: "India",
    optionD: "UK",
    asnwer: "optionB",
    answ: "Fiji",
  },
  {
    id:10,
    prompt: "First Afghan War took place in?",
    optionA: "1839",
    optionB: "1843",
    optionC: "1833",
    optionD: "1848",
    asnwer: "optionA",
    answ: "1839",
  },
];
